package com.bawnorton.plaques.util;

public enum PlaqueType {
    STONE, BLACKSTONE, NETHER_BRICK, PRISMARINE, QUARTZ, SANDSTONE,
    RED_SANDSTONE, BRICK, STONE_BRICK, MOSSY_STONE_BRICK, CRACKED_STONE_BRICK,
    ANDESITE, DIORITE, GRANITE, POLISHED_ANDESITE, POLISHED_DIORITE,
    POLISHED_GRANITE, COBBLESTONE, MOSSY_COBBLESTONE, END_STONE_BRICK, PURPUR;

    public String getName() {
        return name().toLowerCase();
    }
}
